"""initial schema

Revision ID: 41c6f223efd2
Revises: 
Create Date: 2026-09-27 12:25:44.200617
"""
from alembic import op
import sqlalchemy as sa


revision = '41c6f223efd2'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # Existing databases were historically initialized with create_all.
    # Treat this as a non-destructive baseline and create tables only on a clean DB.
    if "tenants" not in set(sa.inspect(op.get_bind()).get_table_names()):
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('audit_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('username', sa.String(length=100), nullable=True),
        sa.Column('action', sa.String(length=100), nullable=False),
        sa.Column('entity_type', sa.String(length=100), nullable=False),
        sa.Column('entity_id', sa.String(length=100), nullable=True),
        sa.Column('ip_address', sa.String(length=50), nullable=True),
        sa.Column('details', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('audit_logs', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
            batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_audit_logs_tenant_id'), ['tenant_id'], unique=False)

        op.create_table('evidence_records',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tender_id', sa.Integer(), nullable=True),
        sa.Column('bidder_id', sa.Integer(), nullable=False),
        sa.Column('document_id', sa.Integer(), nullable=True),
        sa.Column('ocr_result_id', sa.Integer(), nullable=True),
        sa.Column('verification_result_id', sa.Integer(), nullable=True),
        sa.Column('contract_id', sa.Integer(), nullable=True),
        sa.Column('claim_type', sa.String(length=100), nullable=False),
        sa.Column('evidence_text', sa.Text(), nullable=False),
        sa.Column('source_reference', sa.String(length=250), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('evidence_records', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_evidence_records_bidder_id'), ['bidder_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_evidence_records_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_evidence_records_tender_id'), ['tender_id'], unique=False)

        op.create_table('generated_reports',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('report_uid', sa.String(length=64), nullable=False),
        sa.Column('tender_id', sa.Integer(), nullable=False),
        sa.Column('bidder_id', sa.Integer(), nullable=True),
        sa.Column('report_type', sa.String(length=50), nullable=False),
        sa.Column('filename', sa.String(length=250), nullable=False),
        sa.Column('file_hash', sa.String(length=64), nullable=False),
        sa.Column('file_bytes', sa.LargeBinary(), nullable=False),
        sa.Column('generated_by_id', sa.Integer(), nullable=True),
        sa.Column('download_count', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('generated_reports', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_generated_reports_bidder_id'), ['bidder_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_generated_reports_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_generated_reports_report_uid'), ['report_uid'], unique=True)
            batch_op.create_index(batch_op.f('ix_generated_reports_tender_id'), ['tender_id'], unique=False)

        op.create_table('provider_configs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('provider_code', sa.String(length=100), nullable=False),
        sa.Column('provider_name', sa.String(length=200), nullable=False),
        sa.Column('document_type', sa.String(length=50), nullable=False),
        sa.Column('auth_type', sa.String(length=50), nullable=True),
        sa.Column('api_endpoint', sa.String(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('timeout_seconds', sa.Integer(), nullable=True),
        sa.Column('retry_limit', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('provider_code')
        )
        with op.batch_alter_table('provider_configs', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_provider_configs_id'), ['id'], unique=False)

        op.create_table('tenants',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
        )
        with op.batch_alter_table('tenants', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_tenants_id'), ['id'], unique=False)

        op.create_table('bidders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('legal_name', sa.String(length=250), nullable=False),
        sa.Column('trade_name', sa.String(length=250), nullable=True),
        sa.Column('pan', sa.String(length=20), nullable=False),
        sa.Column('gstin', sa.String(length=20), nullable=False),
        sa.Column('cin', sa.String(length=30), nullable=True),
        sa.Column('udyam_number', sa.String(length=50), nullable=True),
        sa.Column('enterprise_type', sa.String(length=50), nullable=True),
        sa.Column('is_startup', sa.Boolean(), nullable=True),
        sa.Column('address', sa.Text(), nullable=False),
        sa.Column('state', sa.String(length=100), nullable=False),
        sa.Column('district', sa.String(length=100), nullable=False),
        sa.Column('contact_email', sa.String(length=150), nullable=False),
        sa.Column('contact_phone', sa.String(length=50), nullable=False),
        sa.Column('contact_person', sa.String(length=150), nullable=False),
        sa.Column('incorporation_date', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('bidders', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_bidders_gstin'), ['gstin'], unique=False)
            batch_op.create_index(batch_op.f('ix_bidders_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_bidders_legal_name'), ['legal_name'], unique=False)
            batch_op.create_index(batch_op.f('ix_bidders_pan'), ['pan'], unique=False)

        op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=200), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('full_name', sa.String(length=200), nullable=False),
        sa.Column('role', sa.String(length=50), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
            batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

        op.create_table('historical_contracts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('bidder_id', sa.Integer(), nullable=False),
        sa.Column('contract_ref', sa.String(length=100), nullable=False),
        sa.Column('procuring_entity', sa.String(length=250), nullable=False),
        sa.Column('title', sa.String(length=300), nullable=False),
        sa.Column('category', sa.String(length=100), nullable=False),
        sa.Column('contract_value_lakhs', sa.Float(), nullable=False),
        sa.Column('issue_date', sa.String(length=50), nullable=False),
        sa.Column('scheduled_completion', sa.String(length=50), nullable=False),
        sa.Column('actual_completion', sa.String(length=50), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('delay_days', sa.Integer(), nullable=True),
        sa.Column('documented_delay_cause', sa.String(length=100), nullable=True),
        sa.Column('liquidated_damages_inr', sa.Float(), nullable=True),
        sa.Column('performance_rating', sa.Float(), nullable=True),
        sa.Column('similarity_score', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('historical_contracts', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_historical_contracts_bidder_id'), ['bidder_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_historical_contracts_contract_ref'), ['contract_ref'], unique=False)
            batch_op.create_index(batch_op.f('ix_historical_contracts_id'), ['id'], unique=False)

        op.create_table('tenders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('tender_ref', sa.String(length=100), nullable=False),
        sa.Column('gem_ref', sa.String(length=100), nullable=True),
        sa.Column('title', sa.String(length=300), nullable=False),
        sa.Column('department', sa.String(length=200), nullable=False),
        sa.Column('category', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('estimated_value_cr', sa.Float(), nullable=True),
        sa.Column('issue_date', sa.String(length=50), nullable=False),
        sa.Column('closing_date', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('pdf_filename', sa.String(length=200), nullable=True),
        sa.Column('pdf_bytes', sa.LargeBinary(), nullable=True),
        sa.Column('created_by_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('tenders', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_tenders_gem_ref'), ['gem_ref'], unique=False)
            batch_op.create_index(batch_op.f('ix_tenders_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_tenders_tender_ref'), ['tender_ref'], unique=True)

        op.create_table('bidder_documents',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('bidder_id', sa.Integer(), nullable=False),
        sa.Column('tender_id', sa.Integer(), nullable=True),
        sa.Column('document_type', sa.String(length=50), nullable=False),
        sa.Column('filename', sa.String(length=250), nullable=False),
        sa.Column('mime_type', sa.String(length=100), nullable=True),
        sa.Column('file_hash', sa.String(length=64), nullable=False),
        sa.Column('file_size_bytes', sa.Integer(), nullable=True),
        sa.Column('version', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('previous_version_id', sa.Integer(), nullable=True),
        sa.Column('is_synthetic', sa.Boolean(), nullable=True),
        sa.Column('storage_path', sa.String(length=255), nullable=True),
        sa.Column('content_bytes', sa.LargeBinary(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], ),
        sa.ForeignKeyConstraint(['previous_version_id'], ['bidder_documents.id'], ),
        sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('bidder_documents', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_bidder_documents_bidder_id'), ['bidder_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_bidder_documents_document_type'), ['document_type'], unique=False)
            batch_op.create_index(batch_op.f('ix_bidder_documents_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_bidder_documents_tender_id'), ['tender_id'], unique=False)

        op.create_table('quality_inspection_records',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('contract_id', sa.Integer(), nullable=False),
        sa.Column('inspection_date', sa.String(length=50), nullable=False),
        sa.Column('inspection_agency', sa.String(length=200), nullable=True),
        sa.Column('result', sa.String(length=50), nullable=True),
        sa.Column('defect_count', sa.Integer(), nullable=True),
        sa.Column('rework_required', sa.Boolean(), nullable=True),
        sa.Column('warranty_claims', sa.Integer(), nullable=True),
        sa.Column('remarks', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['contract_id'], ['historical_contracts.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('quality_inspection_records', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_quality_inspection_records_contract_id'), ['contract_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_quality_inspection_records_id'), ['id'], unique=False)

        op.create_table('tender_bidders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tender_id', sa.Integer(), nullable=False),
        sa.Column('bidder_id', sa.Integer(), nullable=False),
        sa.Column('submission_date', sa.String(length=50), nullable=True),
        sa.Column('compliance_status', sa.String(length=50), nullable=True),
        sa.Column('compliance_score', sa.Float(), nullable=True),
        sa.Column('risk_level', sa.String(length=50), nullable=True),
        sa.Column('final_decision', sa.String(length=50), nullable=True),
        sa.Column('decision_notes', sa.Text(), nullable=True),
        sa.Column('decided_by_id', sa.Integer(), nullable=True),
        sa.Column('decided_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], ),
        sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('tender_bidders', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_tender_bidders_bidder_id'), ['bidder_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_tender_bidders_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_tender_bidders_tender_id'), ['tender_id'], unique=False)

        op.create_table('tender_requirements',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tender_id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('requirement_type', sa.String(length=50), nullable=True),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('structured_rule', sa.JSON(), nullable=True),
        sa.Column('source_page', sa.Integer(), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('approval_status', sa.String(length=50), nullable=True),
        sa.Column('approving_officer_id', sa.Integer(), nullable=True),
        sa.Column('approved_at', sa.DateTime(), nullable=True),
        sa.Column('officer_notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['approving_officer_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('tender_requirements', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_tender_requirements_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_tender_requirements_tender_id'), ['tender_id'], unique=False)

        op.create_table('compliance_results',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tender_bidder_id', sa.Integer(), nullable=False),
        sa.Column('requirement_id', sa.Integer(), nullable=True),
        sa.Column('rule_code', sa.String(length=50), nullable=False),
        sa.Column('rule_name', sa.String(length=200), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('score', sa.Float(), nullable=True),
        sa.Column('explanation', sa.Text(), nullable=False),
        sa.Column('evidence_ids', sa.JSON(), nullable=True),
        sa.Column('evaluated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['requirement_id'], ['tender_requirements.id'], ),
        sa.ForeignKeyConstraint(['tender_bidder_id'], ['tender_bidders.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('compliance_results', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_compliance_results_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_compliance_results_tender_bidder_id'), ['tender_bidder_id'], unique=False)

        op.create_table('ocr_results',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('document_id', sa.Integer(), nullable=False),
        sa.Column('extracted_text', sa.Text(), nullable=False),
        sa.Column('fields', sa.JSON(), nullable=True),
        sa.Column('bounding_boxes', sa.JSON(), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('engine', sa.String(length=100), nullable=True),
        sa.Column('model_version', sa.String(length=100), nullable=True),
        sa.Column('page_count', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['document_id'], ['bidder_documents.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('ocr_results', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_ocr_results_document_id'), ['document_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_ocr_results_id'), ['id'], unique=False)

        op.create_table('risk_assessments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tender_bidder_id', sa.Integer(), nullable=False),
        sa.Column('overall_score', sa.Float(), nullable=True),
        sa.Column('overall_category', sa.String(length=50), nullable=True),
        sa.Column('dimensions', sa.JSON(), nullable=True),
        sa.Column('explanation', sa.Text(), nullable=False),
        sa.Column('contributing_factors', sa.JSON(), nullable=True),
        sa.Column('data_sufficiency', sa.String(length=50), nullable=True),
        sa.Column('model_version', sa.String(length=100), nullable=True),
        sa.Column('assessed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['tender_bidder_id'], ['tender_bidders.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_risk_assessments_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_risk_assessments_tender_bidder_id'), ['tender_bidder_id'], unique=False)

        op.create_table('verification_results',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('document_id', sa.Integer(), nullable=False),
        sa.Column('provider_name', sa.String(length=150), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('raw_response', sa.JSON(), nullable=True),
        sa.Column('discrepancy_notes', sa.Text(), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=True),
        sa.Column('verified_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['document_id'], ['bidder_documents.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('verification_results', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_verification_results_document_id'), ['document_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_verification_results_id'), ['id'], unique=False)

        # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_results_id'))
        batch_op.drop_index(batch_op.f('ix_verification_results_document_id'))

    op.drop_table('verification_results')
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_assessments_tender_bidder_id'))
        batch_op.drop_index(batch_op.f('ix_risk_assessments_id'))

    op.drop_table('risk_assessments')
    with op.batch_alter_table('ocr_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocr_results_id'))
        batch_op.drop_index(batch_op.f('ix_ocr_results_document_id'))

    op.drop_table('ocr_results')
    with op.batch_alter_table('compliance_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_results_tender_bidder_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_results_id'))

    op.drop_table('compliance_results')
    with op.batch_alter_table('tender_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tender_requirements_tender_id'))
        batch_op.drop_index(batch_op.f('ix_tender_requirements_id'))

    op.drop_table('tender_requirements')
    with op.batch_alter_table('tender_bidders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tender_bidders_tender_id'))
        batch_op.drop_index(batch_op.f('ix_tender_bidders_id'))
        batch_op.drop_index(batch_op.f('ix_tender_bidders_bidder_id'))

    op.drop_table('tender_bidders')
    with op.batch_alter_table('quality_inspection_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_inspection_records_id'))
        batch_op.drop_index(batch_op.f('ix_quality_inspection_records_contract_id'))

    op.drop_table('quality_inspection_records')
    with op.batch_alter_table('bidder_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bidder_documents_tender_id'))
        batch_op.drop_index(batch_op.f('ix_bidder_documents_id'))
        batch_op.drop_index(batch_op.f('ix_bidder_documents_document_type'))
        batch_op.drop_index(batch_op.f('ix_bidder_documents_bidder_id'))

    op.drop_table('bidder_documents')
    with op.batch_alter_table('tenders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenders_tender_ref'))
        batch_op.drop_index(batch_op.f('ix_tenders_id'))
        batch_op.drop_index(batch_op.f('ix_tenders_gem_ref'))

    op.drop_table('tenders')
    with op.batch_alter_table('historical_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_contracts_id'))
        batch_op.drop_index(batch_op.f('ix_historical_contracts_contract_ref'))
        batch_op.drop_index(batch_op.f('ix_historical_contracts_bidder_id'))

    op.drop_table('historical_contracts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('bidders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bidders_pan'))
        batch_op.drop_index(batch_op.f('ix_bidders_legal_name'))
        batch_op.drop_index(batch_op.f('ix_bidders_id'))
        batch_op.drop_index(batch_op.f('ix_bidders_gstin'))

    op.drop_table('bidders')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_id'))

    op.drop_table('tenants')
    with op.batch_alter_table('provider_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_configs_id'))

    op.drop_table('provider_configs')
    with op.batch_alter_table('generated_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_reports_tender_id'))
        batch_op.drop_index(batch_op.f('ix_generated_reports_report_uid'))
        batch_op.drop_index(batch_op.f('ix_generated_reports_id'))
        batch_op.drop_index(batch_op.f('ix_generated_reports_bidder_id'))

    op.drop_table('generated_reports')
    with op.batch_alter_table('evidence_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_records_tender_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_records_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_records_bidder_id'))

    op.drop_table('evidence_records')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
